import { Notice } from "@/components/app-shell/ui";
import { money } from "@/lib/finance/service";

export function FinancePage({ children }) { return <main className="min-w-0 overflow-x-hidden px-5 py-8 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1480px]">{children}</div></main>; }
export function SchemaNotice() { return <Notice type="warning" title="Financeiro 2.0 aguardando ativação">Em instalação nova, aplique as migrations `20260827100000` a `20260828100000` na ordem indicada na documentação. Em banco que recebeu as quatro migrations iniciais, aplique apenas a consolidação `20260827103000` e depois `20260828100000_financeiro_2_comissoes_eventos.sql`.</Notice>; }
export function Metric({ label, value, detail }) { return <section className="premium-panel min-w-0 rounded-lg p-5"><p className="text-sm font-semibold text-neutral-500">{label}</p><strong className="mt-2 block text-2xl font-black">{typeof value === "number" ? money(value) : value}</strong>{detail ? <p className="mt-2 text-xs text-neutral-500">{detail}</p> : null}</section>; }
export function StatusPill({ status }) { const tone = status === "pago" || status === "conciliado" ? "bg-emerald-50 text-emerald-700" : status === "vencido" || status === "divergente" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-800"; return <span className={`rounded-full px-2 py-1 text-xs font-bold ${tone}`}>{status}</span>; }
export function FinanceTable({ columns, rows, empty = "Nenhum registro no período." }) { return <div className="overflow-x-auto rounded-lg border border-neutral-200 bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase text-neutral-500"><tr>{columns.map(c=><th key={c.key} className="px-4 py-3">{c.label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row,i)=><tr key={row.id || i} className="border-t border-neutral-100">{columns.map(c=><td key={c.key} className="px-4 py-3 text-neutral-700">{c.render ? c.render(row) : row[c.key] ?? "-"}</td>)}</tr>) : <tr><td colSpan={columns.length} className="px-4 py-8 text-center text-neutral-500">{empty}</td></tr>}</tbody></table></div>; }
export function ExportCsvLink({ report, month }) { const query=new URLSearchParams({relatorio:report,month}); return <a className="inline-flex h-10 items-center rounded-lg border border-neutral-300 bg-white px-4 text-sm font-bold text-neutral-800 transition hover:border-neutral-950" href={`/dashboard/financeiro/export?${query.toString()}`}>Exportar CSV</a>; }
