const group = (conditions = []) => ({ kind: "group", operator: "AND", conditions });
const predicate = (field, operator, value, valueType = "string") => ({ kind: "predicate", field, operator, value, valueType });
const base = (trigger, steps, conditions = []) => ({ schemaVersion: 1, trigger: { type: trigger, reentry: "deny_self" }, conditions: group(conditions), steps });

export const AUTOMATION_TEMPLATES = Object.freeze([
  { id: "new-lead-no-contact", name: "Novo lead sem contato", description: "Cria follow-up quando um lead novo não recebe contato em dez minutos.", definition: base("crm.opportunity.created", [{ id: "wait_contact", type: "wait", mode: "duration", amount: 10, unit: "minutes", until: null }, { id: "still_without_owner", type: "condition", conditions: group([predicate("opportunity.first_response_at", "is_empty", null, "datetime")]) }, { id: "create_follow_up", type: "action", actionType: "crm.create_follow_up", params: { title: "Entrar em contato com novo lead", due_in_minutes: 0 } }]) },
  { id: "stalled-opportunity", name: "Oportunidade parada", description: "Cria follow-up quando a oportunidade permanece na etapa selecionada.", definition: base("crm.stage.changed", [{ id: "wait_three_days", type: "wait", mode: "duration", amount: 3, unit: "days", until: null }, { id: "same_stage", type: "condition", conditions: group([predicate("opportunity.stage_id", "equals", "", "reference")]) }, { id: "follow_up", type: "action", actionType: "crm.create_follow_up", params: { title: "Retomar oportunidade parada", due_in_minutes: 0 } }]) },
  { id: "appointment-reminder", name: "Lembrete de agendamento", description: "Registra o lembrete no canal configurado.", definition: base("booking.created", [{ id: "reminder", type: "action", actionType: "agenda.register_reminder", params: { channel: "interno", message: "Lembrete de atendimento" } }]) },
  { id: "receivable-due-soon", name: "Recebível próximo do vencimento", description: "Cria tarefa de cobrança se o recebível seguir aberto.", definition: base("finance.receivable.due_soon", [{ id: "still_open", type: "condition", conditions: group([predicate("receivable.status", "in", ["aberto", "parcial"], "enum")]) }, { id: "collection", type: "action", actionType: "finance.create_collection_task", params: { title: "Cobrar recebível próximo do vencimento", due_in_minutes: 0 } }]) },
  { id: "overdue", name: "Recuperação de inadimplência", description: "Cria tarefa para um recebível vencido.", definition: base("finance.receivable.overdue", [{ id: "collection", type: "action", actionType: "finance.create_collection_task", params: { title: "Cobrar recebível vencido", due_in_minutes: 0 } }]) },
  { id: "payment-confirmed", name: "Pagamento confirmado", description: "Registra notificação interna após a confirmação financeira.", definition: base("payment.received", [{ id: "notify", type: "action", actionType: "internal.create_notification", params: { title: "Pagamento confirmado", message: "O recebimento foi confirmado pelo Financeiro 2.0." } }]) },
  { id: "patient-return", name: "Retorno de paciente", description: "Cria follow-up trinta dias após um atendimento concluído.", definition: base("booking.completed", [{ id: "wait_return", type: "wait", mode: "duration", amount: 30, unit: "days", until: null }, { id: "return_notification", type: "action", actionType: "internal.create_notification", params: { title: "Retorno recomendado", message: "Verifique se o paciente já possui novo atendimento." } }]) },
  { id: "no-show", name: "Recuperação de falta", description: "Cria uma notificação para recuperar um cliente que faltou.", definition: base("booking.no_show", [{ id: "notify_no_show", type: "action", actionType: "internal.create_notification", params: { title: "Recuperar cliente com falta", message: "Entre em contato para oferecer um novo horário." } }]) },
]);

export function getAutomationTemplate(id) { return AUTOMATION_TEMPLATES.find((item) => item.id === id) || null; }
