import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const files=["20260827100000_financeiro_2_core.sql","20260827101000_financeiro_2_rpcs.sql","20260827101500_financeiro_2_operacoes.sql","20260827102000_financeiro_2_backfill.sql"];
test("migrations financeiras são aditivas e transacionais",async()=>{ for(const file of files){ const sql=await readFile(new URL(`../supabase/migrations/${file}`,import.meta.url),"utf8"); assert.match(sql,/^begin;/i,file); assert.match(sql,/commit;\s*$/i,file); assert.doesNotMatch(sql,/drop\s+table|truncate\s|delete\s+from/i,file); } });
test("núcleo possui tenant, RLS e idempotência",async()=>{ const sql=await readFile(new URL("../supabase/migrations/20260827100000_financeiro_2_core.sql",import.meta.url),"utf8"); assert.match(sql,/clinica_id uuid not null/g); assert.match(sql,/enable row level security/); assert.match(sql,/unique \(clinica_id,idempotency_key\)/); assert.doesNotMatch(sql,/on all tables in schema/i); });
test("RPCs bloqueiam excesso e exigem idempotência",async()=>{ const sql=await readFile(new URL("../supabase/migrations/20260827101000_financeiro_2_rpcs.sql",import.meta.url),"utf8"); assert.match(sql,/Chave de idempotência obrigatória/); assert.match(sql,/excede o saldo aberto/); assert.match(sql,/for update/); });
test("cancelamento canônico estorna caixa antes de cancelar o recebível",async()=>{ const sql=await readFile(new URL("../supabase/migrations/20260827101500_financeiro_2_operacoes.sql",import.meta.url),"utf8"); assert.match(sql,/finance_cancelar_recebivel_origem/); assert.match(sql,/finance_estornar_liquidacao/); assert.match(sql,/status='cancelado'/); assert.match(sql,/cancelamento:/); });
test("pacote reconhece competência por sessão com ajuste final de centavos",async()=>{ const sql=await readFile(new URL("../supabase/migrations/20260827101500_financeiro_2_operacoes.sql",import.meta.url),"utf8"); assert.match(sql,/finance_reconhecer_sessao_pacote/); assert.match(sql,/v_unitario:=trunc/); assert.match(sql,/v_pacote\.valor_total-\(v_unitario\*/); assert.match(sql,/sessao_pacote/); });
