"use client";
import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Beaker, Clock3, Plus, Trash2, Zap } from "lucide-react";
import { EVENT_REGISTRY } from "@/lib/automations/registry/events.mjs";
import { ACTION_REGISTRY } from "@/lib/automations/registry/actions.mjs";
import { OPERATOR_REGISTRY } from "@/lib/automations/registry/operators.mjs";
import { dryRunAutomation } from "@/lib/automations/compiler.mjs";

function uid(prefix) { return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`; }
function Input({ className = "", ...props }) { return <input {...props} className={`dashboard-field min-h-11 rounded-lg border border-neutral-200 bg-white px-3 text-sm ${className}`} />; }
function Select({ className = "", ...props }) { return <select {...props} className={`dashboard-field min-h-11 rounded-lg border border-neutral-200 bg-white px-3 text-sm ${className}`} />; }

export function AutomationBuilder({ automation, saveAction }) {
  const [definition, setDefinition] = useState(automation.draft_definition || {});
  const [timeline, setTimeline] = useState([]);
  const event = EVENT_REGISTRY[definition.trigger?.type] || Object.values(EVENT_REGISTRY)[0];
  const conditions = definition.conditions?.conditions || [];
  const steps = definition.steps || [];
  const update = (patch) => setDefinition((current) => ({ ...current, ...patch }));
  const updateCondition = (index, patch) => update({ conditions: { ...(definition.conditions || { kind: "group", operator: "AND" }), conditions: conditions.map((item, i) => i === index ? { ...item, ...patch } : item) } });
  const updateStep = (index, patch) => update({ steps: steps.map((item, i) => i === index ? { ...item, ...patch } : item) });
  const fieldMap = useMemo(() => Object.fromEntries((event?.fields || []).map((item) => [item.path, item])), [event]);
  const test = () => { try { setTimeline(dryRunAutomation(definition, { event: { payload: {} }, opportunity: {}, booking: {}, receivable: {} }).timeline); } catch (error) { setTimeline([{ status: "failed", message: error.details?.join(" ") || error.message }]); } };
  return <div className="space-y-5">
    <form action={saveAction} className="space-y-5">
      <input type="hidden" name="automation_id" value={automation.id} /><input type="hidden" name="current_status" value={automation.status} /><input type="hidden" name="definition_json" value={JSON.stringify(definition)} />
      <section className="premium-panel rounded-lg p-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Nome<Input name="name" defaultValue={automation.name} required className="mt-2 w-full" /></label><label className="text-sm font-bold">Descrição<Input name="description" defaultValue={automation.description || ""} className="mt-2 w-full" /></label></div></section>
      <section className="premium-panel rounded-lg p-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--clinic-primary)]">Quando</p><Select aria-label="Evento" value={event?.type || ""} onChange={(e) => update({ trigger: { type: e.target.value, reentry: "deny_self" }, conditions: { kind: "group", operator: "AND", conditions: [] } })} className="mt-3 w-full"><option value="">Selecione um evento</option>{Object.values(EVENT_REGISTRY).map((item) => <option key={item.type} value={item.type}>{item.module} · {item.label}</option>)}</Select><p className="mt-2 text-sm text-neutral-500">{event?.description}</p></section>
      <section className="premium-panel rounded-lg p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--clinic-primary)]">Se</p><h2 className="mt-1 text-lg font-black">Condições iniciais</h2></div><Select aria-label="Operador do grupo" value={definition.conditions?.operator || "AND"} onChange={(e) => update({ conditions: { ...definition.conditions, operator: e.target.value } })}><option value="AND">Todas (E)</option><option value="OR">Qualquer uma (OU)</option></Select></div>
        <div className="mt-4 space-y-3">{conditions.map((condition, index) => { const selectedField = fieldMap[condition.field] || event?.fields?.[0]; return <div key={`${condition.field}-${index}`} className="grid gap-2 rounded-lg border border-neutral-200 bg-white/70 p-3 md:grid-cols-[1.3fr_1fr_1fr_auto]">
          <Select aria-label="Campo" value={condition.field} onChange={(e) => { const next = fieldMap[e.target.value]; updateCondition(index, { field: e.target.value, valueType: next?.type || "string" }); }}>{event?.fields.map((item) => <option key={item.path} value={item.path}>{item.label}</option>)}</Select>
          <Select aria-label="Operador" value={condition.operator} onChange={(e) => updateCondition(index, { operator: e.target.value })}>{Object.values(OPERATOR_REGISTRY).filter((item) => item.types.includes(selectedField?.type || "string")).map((item) => <option key={item.type} value={item.type}>{item.label}</option>)}</Select>
          {!['is_empty','is_not_empty'].includes(condition.operator) ? <Input aria-label="Valor" value={Array.isArray(condition.value) ? condition.value.join(",") : condition.value ?? ""} onChange={(e) => updateCondition(index, { value: ["in", "not_in", "between"].includes(condition.operator) ? e.target.value.split(",").map((item) => item.trim()) : e.target.value })} /> : <div />}
          <button type="button" title="Remover condição" onClick={() => update({ conditions: { ...definition.conditions, conditions: conditions.filter((_, i) => i !== index) } })} className="inline-flex h-11 w-11 items-center justify-center rounded-lg border border-neutral-200 text-red-600"><Trash2 size={17} /></button>
        </div>; })}</div>
        <button type="button" onClick={() => { const first = event?.fields?.[0]; if (first) update({ conditions: { ...definition.conditions, conditions: [...conditions, { kind: "predicate", field: first.path, operator: "equals", valueType: first.type, value: "" }] } }); }} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-neutral-200 bg-white px-4 py-2 text-sm font-bold"><Plus size={16} /> Condição</button>
      </section>
      <section className="premium-panel rounded-lg p-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--clinic-primary)]">Então</p><h2 className="mt-1 text-lg font-black">Etapas da automação</h2>
        <div className="mt-4 space-y-3">{steps.map((step, index) => <div key={step.id} className="rounded-lg border border-neutral-200 bg-white/75 p-4"><div className="flex items-center gap-3"><span className="inline-flex h-9 w-9 items-center justify-center rounded-lg bg-[var(--clinic-soft)] text-[var(--clinic-primary)]">{step.type === "wait" ? <Clock3 size={18} /> : <Zap size={18} />}</span><strong className="flex-1">{step.type === "wait" ? "Aguardar" : "Executar ação"}</strong><button type="button" title="Subir" disabled={index === 0} onClick={() => { const copy = [...steps]; [copy[index - 1], copy[index]] = [copy[index], copy[index - 1]]; update({ steps: copy }); }}><ArrowUp size={17} /></button><button type="button" title="Descer" disabled={index === steps.length - 1} onClick={() => { const copy = [...steps]; [copy[index + 1], copy[index]] = [copy[index], copy[index + 1]]; update({ steps: copy }); }}><ArrowDown size={17} /></button><button type="button" title="Remover" onClick={() => update({ steps: steps.filter((_, i) => i !== index) }} className="text-red-600"><Trash2 size={17} /></button></div>
          {step.type === "wait" ? <div className="mt-3 grid gap-2 sm:grid-cols-2"><Input aria-label="Duração" type="number" min="1" value={step.amount} onChange={(e) => updateStep(index, { amount: Number(e.target.value) })} /><Select aria-label="Unidade" value={step.unit} onChange={(e) => updateStep(index, { unit: e.target.value })}><option value="minutes">Minutos</option><option value="hours">Horas</option><option value="days">Dias</option></Select></div> : <div className="mt-3 space-y-3"><Select aria-label="Ação" value={step.actionType} onChange={(e) => updateStep(index, { actionType: e.target.value, params: {} })} className="w-full">{Object.values(ACTION_REGISTRY).map((item) => <option key={item.type} value={item.type}>{item.module} · {item.label}</option>)}</Select><div className="grid gap-2 sm:grid-cols-2">{(ACTION_REGISTRY[step.actionType]?.parameters || []).map((param) => <label key={param.name} className="text-xs font-bold text-neutral-600">{param.label}{param.type === "enum" ? <Select value={step.params?.[param.name] || ""} onChange={(e) => updateStep(index, { params: { ...step.params, [param.name]: e.target.value } })} className="mt-1 w-full"><option value="">Selecione</option>{param.options.map((option) => <option key={option} value={option}>{option}</option>)}</Select> : <Input type={["number","money"].includes(param.type) ? "number" : "text"} value={step.params?.[param.name] || ""} onChange={(e) => updateStep(index, { params: { ...step.params, [param.name]: ["number","money"].includes(param.type) ? Number(e.target.value) : e.target.value } })} className="mt-1 w-full" />}</label>)}</div></div>}
        </div>)}</div>
        <div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => update({ steps: [...steps, { id: uid("action"), type: "action", actionType: "internal.create_notification", params: { title: "Notificação", message: "Revise esta ocorrência." } }] })} className="inline-flex items-center gap-2 rounded-lg bg-neutral-950 px-4 py-2 text-sm font-bold text-white"><Plus size={16} /> Ação</button><button type="button" onClick={() => update({ steps: [...steps, { id: uid("wait"), type: "wait", mode: "duration", amount: 10, unit: "minutes", until: null }] })} className="inline-flex items-center gap-2 rounded-lg border border-neutral-200 bg-white px-4 py-2 text-sm font-bold"><Clock3 size={16} /> Espera</button></div>
      </section>
      <div className="flex flex-wrap justify-end gap-3"><button type="button" onClick={test} className="inline-flex items-center gap-2 rounded-lg border border-neutral-300 bg-white px-5 py-3 font-bold"><Beaker size={18} /> Testar sem executar</button><button type="submit" className="rounded-lg bg-neutral-950 px-6 py-3 font-bold text-white">Salvar rascunho</button></div>
    </form>
    {timeline.length ? <section className="premium-panel rounded-lg p-5"><h2 className="text-lg font-black">Resultado do teste</h2><div className="mt-4 space-y-2">{timeline.map((item, index) => <div key={`${item.stepId || item.type}-${index}`} className="rounded-lg border border-neutral-200 bg-white/75 p-3 text-sm"><strong className={item.status === "failed" ? "text-red-700" : "text-neutral-900"}>{item.status === "failed" ? "Falha" : item.status === "skipped" ? "Simulação" : "OK"}</strong><span className="ml-2 text-neutral-600">{item.message}</span></div>)}</div></section> : null}
  </div>;
}
