import Link from "next/link";
import { PageHeader, Notice, SubmitButton } from "@/components/app-shell/ui";
import { PipelineStageList } from "@/components/crm/pipeline-stage-list";
import { requireClinicSection } from "@/lib/auth/session";
import { getCrmWorkspace } from "@/lib/crm/service";
import { createCrmPipelineAction, createCrmTagAction, createLostReasonAction, createPipelineStageAction, setDefaultCrmPipelineAction, updateProcedureCrmBehaviorAction } from "../actions";

export const metadata = { title: "Configurações do CRM | NexaWi Clínicas" };

export default async function CrmSettingsPage({ searchParams }) {
  const params = await searchParams;
  const { activeClinic } = await requireClinicSection("crm");
  const workspace = await getCrmWorkspace(activeClinic.id, { pipelineId: params?.pipeline || null });
  return <main className="min-w-0 px-4 py-8 sm:px-6 lg:px-8"><section className="mx-auto max-w-[1480px]">
    <PageHeader eyebrow="CRM 2.0" title="Configurações do funil" description="Personalize etapas, probabilidades, motivos de perda e o comportamento comercial dos procedimentos." action={<Link href="/dashboard/crm" className="inline-flex h-10 items-center rounded-lg border border-neutral-300 bg-white px-4 text-sm font-bold">Voltar ao CRM</Link>} />
    {!workspace.available ? <div className="mt-6"><Notice type="warning">Aplique as migrations do CRM 2.0 antes de configurar o funil.</Notice></div> : <div className="mt-6 space-y-6">
      <section className="premium-panel rounded-lg p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-lg font-black">Pipelines</h2><p className="mt-1 text-sm text-neutral-600">Separe jornadas comerciais diferentes sem misturar oportunidades ou etapas.</p><nav className="mt-3 flex max-w-full gap-2 overflow-x-auto pb-1" aria-label="Pipelines configurados">{workspace.pipelines.map((pipeline) => <Link key={pipeline.id} href={`/dashboard/crm/configuracoes?pipeline=${pipeline.id}`} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-black ${pipeline.id === workspace.selectedPipelineId ? "border-transparent bg-neutral-950 text-white" : "border-neutral-200 bg-white text-neutral-600"}`}>{pipeline.nome}{pipeline.padrao ? " · padrão" : ""}</Link>)}</nav></div><div className="flex flex-wrap gap-2">{!workspace.pipelines.find((pipeline) => pipeline.id === workspace.selectedPipelineId)?.padrao ? <form action={setDefaultCrmPipelineAction}><input type="hidden" name="pipeline_id" value={workspace.selectedPipelineId} /><button className="h-11 rounded-lg border border-neutral-300 bg-white px-4 text-sm font-bold">Definir como padrão</button></form> : null}</div></div><form action={createCrmPipelineAction} className="mt-5 grid gap-3 border-t border-neutral-200 pt-5 sm:grid-cols-[1fr_auto_auto] sm:items-end"><label><span className="text-sm font-semibold">Novo pipeline</span><input className="dashboard-field mt-2 h-11 w-full rounded-lg border border-neutral-200 px-3" name="nome" placeholder="Ex.: Jornada de avaliação" required /></label><label className="flex h-11 items-center gap-2 rounded-lg border border-neutral-200 px-3 text-sm font-bold"><input type="checkbox" name="padrao" /> Tornar padrão</label><SubmitButton>Criar pipeline</SubmitButton></form></section>
      <section className="premium-panel rounded-lg p-5"><h2 className="text-lg font-black">Etapas do pipeline</h2><p className="mt-1 text-sm text-neutral-600">Arraste para reordenar. A probabilidade alimenta o valor ponderado do funil.</p><div className="mt-4"><PipelineStageList initialStages={workspace.stages} pipelineId={workspace.selectedPipelineId} /></div>
        <form action={createPipelineStageAction} className="mt-5 grid gap-3 border-t border-neutral-200 pt-5 md:grid-cols-[1.5fr_100px_130px_150px_auto] md:items-end"><input type="hidden" name="pipeline_id" value={workspace.selectedPipelineId} /><label><span className="text-sm font-semibold">Nova etapa</span><input className="dashboard-field mt-2 h-11 w-full rounded-lg border border-neutral-200 px-3" name="nome" required /></label><label><span className="text-sm font-semibold">Cor</span><input className="dashboard-field mt-2 h-11 w-full rounded-lg border border-neutral-200 px-2" type="color" name="cor" defaultValue="#64748b" /></label><label><span className="text-sm font-semibold">Probabilidade</span><input className="dashboard-field mt-2 h-11 w-full rounded-lg border border-neutral-200 px-3" type="number" name="probabilidade" min="0" max="100" defaultValue="20" /></label><label><span className="text-sm font-semibold">Tipo</span><select className="dashboard-field mt-2 h-11 w-full rounded-lg border border-neutral-200 bg-white px-3" name="tipo"><option value="open">Em aberto</option><option value="won">Ganho</option><option value="lost">Perdido</option></select></label><SubmitButton>Adicionar</SubmitButton></form>
      </section>
      <div className="grid gap-6 lg:grid-cols-2"><section className="premium-panel rounded-lg p-5"><h2 className="text-lg font-black">Motivos de perda</h2><div className="mt-4 flex flex-wrap gap-2">{workspace.lostReasons.map((item) => <span key={item.id} className="rounded-full bg-neutral-100 px-3 py-2 text-sm font-bold">{item.nome}</span>)}</div><form action={createLostReasonAction} className="mt-4 flex gap-2"><input className="dashboard-field h-11 min-w-0 flex-1 rounded-lg border border-neutral-200 px-3" name="nome" placeholder="Novo motivo" required /><input type="hidden" name="ordem" value={workspace.lostReasons.length * 10 + 10} /><SubmitButton>Adicionar</SubmitButton></form></section><section className="premium-panel rounded-lg p-5"><h2 className="text-lg font-black">Tags comerciais</h2><div className="mt-4 flex flex-wrap gap-2">{workspace.tags.map((item) => <span key={item.id} className="rounded-full border px-3 py-2 text-sm font-bold" style={{ borderColor: item.cor, color: item.cor }}>{item.nome}</span>)}</div><form action={createCrmTagAction} className="mt-4 grid grid-cols-[1fr_70px_auto] gap-2"><input className="dashboard-field h-11 min-w-0 rounded-lg border border-neutral-200 px-3" name="nome" placeholder="Nova tag" required /><input className="dashboard-field h-11 rounded-lg border border-neutral-200 px-2" type="color" name="cor" defaultValue="#64748b" /><SubmitButton>Adicionar</SubmitButton></form></section></div>
      <section className="premium-panel rounded-lg p-5"><h2 className="text-lg font-black">Procedimentos e CRM</h2><p className="mt-1 text-sm text-neutral-600">Defina quando um agendamento público deve abrir oportunidade. Contato e agendamento continuam sendo entidades separadas.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{workspace.procedures.map((procedure) => <form action={updateProcedureCrmBehaviorAction} key={procedure.id} className="grid gap-2 rounded-lg border border-neutral-200 p-3 sm:grid-cols-[1fr_190px_auto] sm:items-end"><input type="hidden" name="procedimento_id" value={procedure.id} /><p className="self-center text-sm font-bold">{procedure.nome}</p><label><span className="text-xs text-neutral-500">Comportamento</span><select className="dashboard-field mt-1 h-10 w-full rounded-lg border border-neutral-200 bg-white px-2" name="crm_booking_behavior" defaultValue={procedure.crm_booking_behavior || "none"}><option value="none">Não criar oportunidade</option><option value="evaluation">Avaliação</option><option value="opportunity">Criar oportunidade</option><option value="direct_sale">Venda direta</option></select></label><button className="h-10 rounded-lg border border-neutral-300 px-3 text-sm font-bold">Salvar</button></form>)}</div></section>
    </div>}
  </section></main>;
}
