import Link from "next/link";
import { Activity, CheckCircle2, CircleAlert, Clock3, MessageCircleMore, RefreshCw, ShieldCheck, Unplug, Webhook } from "lucide-react";
import { PageHeader, Notice } from "@/components/app-shell/ui";
import { requireClinicSection } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { getCurrentMembership } from "@/lib/auth/permissions";
import { maskPhone } from "@/lib/whatsapp/core.mjs";
import { isMetaConfigured } from "@/lib/whatsapp/meta/client";
import { EmbeddedSignupButton } from "./embedded-signup-button";
import { checkWhatsAppHealthAction, disconnectWhatsAppAction, submitWhatsAppTemplatesAction, syncWhatsAppTemplatesAction, updateWhatsAppAutomationsAction } from "./actions";

export const metadata = { title: "WhatsApp | NexaWi Clínicas" };
const TABS = [["conexao","Conexão"],["automacoes","Automações"],["mensagens","Mensagens"],["templates","Templates"],["saude","Saúde"]];
const STATUS_LABELS = { APPROVED: "Aprovado", PENDING: "Pendente", REJECTED: "Rejeitado", PAUSED: "Pausado", DISABLED: "Desativado", IN_APPEAL: "Em análise", PENDING_DELETION: "Exclusão pendente", DELETED: "Excluído", LIMIT_EXCEEDED: "Limite excedido" };
const MESSAGE_LABELS = { submitted: "Submetida", sent: "Enviada", delivered: "Entregue", read: "Lida", failed: "Falhou", received: "Recebida", queued: "Na fila" };
const PURPOSE_LABELS = { booking_created: "Novo agendamento", booking_payment_pending: "Pagamento pendente", payment_expiring: "Pagamento perto do vencimento", payment_confirmed: "Pagamento confirmado", payment_expired: "Pagamento expirado", appointment_reminder_24h: "Lembrete 24h", appointment_reminder_3h: "Lembrete 3h", booking_cancelled: "Cancelamento", booking_rescheduled: "Remarcação" };
function date(value) { return value ? new Date(value).toLocaleString("pt-BR") : "-"; }
function bool(value) { return value ? <span className="inline-flex items-center gap-1 font-bold text-emerald-700"><CheckCircle2 size={15}/> OK</span> : <span className="inline-flex items-center gap-1 font-bold text-amber-700"><CircleAlert size={15}/> Pendente</span>; }
function TabNav({ active }) { return <nav className="mt-6 flex gap-2 overflow-x-auto rounded-lg border border-neutral-200 bg-white p-2 shadow-sm">{TABS.map(([key,label]) => <Link key={key} href={`/dashboard/whatsapp?tab=${key}`} className={`shrink-0 rounded-lg px-4 py-2.5 text-sm font-black transition ${active === key ? "bg-neutral-950 text-white shadow-lg" : "text-neutral-600 hover:bg-neutral-50"}`}>{label}</Link>)}</nav>; }

export default async function WhatsAppPage({ searchParams }) {
  const params = await searchParams; const active = TABS.some(([key]) => key === params?.tab) ? params.tab : "conexao";
  const context = await requireClinicSection("whatsapp"); const clinic = context.activeClinic; const membership = getCurrentMembership(context.memberships, clinic.id); const manager = ["owner","admin"].includes(membership?.papel);
  const supabase = await createClient();
  const [connectionResult, settingsResult, templatesResult, messagesResult, jobsResult, webhookResult] = await Promise.all([
    supabase.from("whatsapp_connections").select("*").eq("clinica_id",clinic.id).eq("is_primary",true).maybeSingle(),
    supabase.from("whatsapp_automation_settings").select("*").eq("clinica_id",clinic.id).maybeSingle(),
    supabase.from("whatsapp_templates").select("*").eq("clinica_id",clinic.id).order("purpose"),
    supabase.from("whatsapp_messages").select("id,cliente_id,agendamento_id,direction,message_type,template_name,status,trigger,error_code,error_message,created_at,clientes(nome)").eq("clinica_id",clinic.id).order("created_at",{ascending:false}).limit(50),
    supabase.from("notification_jobs").select("id,status",{count:"exact"}).eq("clinica_id",clinic.id).in("status",["pending","retry","failed"]),
    supabase.from("whatsapp_webhook_events").select("received_at").eq("clinica_id",clinic.id).order("received_at",{ascending:false}).limit(1).maybeSingle(),
  ]);
  const schemaMissing = [connectionResult,settingsResult,templatesResult,messagesResult].some((result) => ["42P01","PGRST205"].includes(result.error?.code));
  const connection = connectionResult.data; const settings = settingsResult.data || {}; const templates = templatesResult.data || []; const messages = messagesResult.data || [];
  const approved = templates.filter((item) => item.status === "APPROVED").length; const failedJobs = (jobsResult.data || []).filter((item) => item.status === "failed").length;
  return <main className="min-w-0 overflow-x-hidden px-4 py-8 sm:px-6 lg:px-10">
    <section className="mx-auto max-w-[1480px]">
    <PageHeader eyebrow="Comunicação oficial" title="WhatsApp Cloud API" description="Conexão oficial da Meta, automações transacionais, templates, entrega real e diagnóstico por clínica." />
    {schemaMissing ? <div className="mt-6"><Notice type="warning" title="Migration pendente">Aplique a migration <strong>20260826100000_whatsapp_meta_official.sql</strong> para ativar este módulo.</Notice></div> : null}
    {!isMetaConfigured() ? <div className="mt-6"><Notice type="warning" title="Configuração central pendente">WhatsApp Meta ainda não configurado. O restante do sistema continua funcionando normalmente.</Notice></div> : null}
    <TabNav active={active}/>

    {active === "conexao" ? <section className="premium-panel mt-6 rounded-lg p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">Conexão principal</h2><p className="mt-1 text-sm text-neutral-500">A clínica autoriza os próprios ativos dentro do fluxo oficial da Meta.</p></div>{manager && !connection ? <EmbeddedSignupButton/> : null}</div>
      {connection ? <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Status",connection.onboarding_status === "ready" ? "Pronto" : connection.onboarding_status],["Número",connection.display_phone_number || "Aguardando"],["Nome verificado",connection.verified_name || "Aguardando"],["Qualidade",connection.quality_rating || "Sem leitura"],["Provider","Meta Cloud API"],["Cobrança",connection.billing_mode === "client_direct" ? "Direta da clínica" : "Linha NexaWi"],["Modo",connection.connection_mode === "cloud_only" ? "Cloud API" : "Coexistence"],["Último health check",date(connection.last_health_check_at)]].map(([label,value]) => <div key={label} className="rounded-lg border border-neutral-200 bg-white p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-neutral-500">{label}</p><p className="mt-2 break-words font-black">{value}</p></div>)}</div> : <div className="mt-6 rounded-lg border border-dashed border-neutral-300 bg-neutral-50 p-8 text-center"><MessageCircleMore className="mx-auto text-[#25D366]" size={36}/><h3 className="mt-3 font-black">Nenhum WhatsApp conectado</h3><p className="mx-auto mt-2 max-w-xl text-sm text-neutral-500">Use o Embedded Signup. Tokens e IDs técnicos não precisam ser digitados pela clínica.</p></div>}
      {connection?.last_error ? <div className="mt-4"><Notice type="warning" title="Atenção operacional">{connection.last_error}</Notice></div> : null}
      {manager && connection ? <div className="mt-5 flex flex-wrap gap-2"><form action={checkWhatsAppHealthAction}><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-neutral-950 px-4 text-sm font-bold text-white"><Activity size={16}/> Testar conexão</button></form><form action={disconnectWhatsAppAction}><button className="inline-flex h-10 items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 text-sm font-bold text-red-700"><Unplug size={16}/> Desconectar</button></form></div> : null}
    </section> : null}

    {active === "automacoes" ? <form action={updateWhatsAppAutomationsAction} className="premium-panel mt-6 rounded-lg p-5 sm:p-6"><div><h2 className="text-xl font-black">Automações transacionais</h2><p className="mt-1 text-sm text-neutral-500">A mensagem só entra na fila com opt-in ativo, conexão pronta e template aprovado.</p></div><label className="mt-5 flex items-center gap-3 rounded-lg border border-neutral-200 bg-white p-4 font-black"><input type="checkbox" name="enabled" defaultChecked={settings.enabled}/> Ativar automações oficiais desta clínica</label><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[["booking_created_enabled","Novo agendamento"],["payment_pending_enabled","Pagamento pendente"],["payment_confirmed_enabled","Pagamento confirmado"],["payment_expiring_enabled","Pagamento perto do vencimento"],["payment_expired_enabled","Pagamento expirado"],["reminder_24h_enabled","Lembrete 24h"],["reminder_3h_enabled","Lembrete 3h"],["booking_cancelled_enabled","Cancelamento"],["booking_rescheduled_enabled","Remarcação"]].map(([name,label]) => <label key={name} className="flex items-center gap-3 rounded-lg border border-neutral-200 bg-white p-4 text-sm font-bold"><input type="checkbox" name={name} defaultChecked={settings[name] ?? true}/>{label}</label>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><label className="text-sm font-bold">Privacidade<select name="privacy_mode" defaultValue={settings.privacy_mode || "discreto"} className="dashboard-field mt-2 h-11 w-full rounded-lg border px-3"><option value="discreto">Discreto</option><option value="detalhado">Detalhado</option></select></label>{[["payment_expiring_minutes","Avisar antes do vencimento",settings.payment_expiring_minutes||60,5,10080],["payment_expiration_minutes","Prazo do pagamento",settings.payment_expiration_minutes||1440,15,43200],["reminder_24h_minutes","Lembrete principal",settings.reminder_24h_minutes||1440,60,10080],["reminder_3h_minutes","Lembrete próximo",settings.reminder_3h_minutes||180,15,1440]].map(([name,label,value,min,max]) => <label key={name} className="text-sm font-bold">{label} (min)<input name={name} type="number" min={min} max={max} defaultValue={value} className="dashboard-field mt-2 h-11 w-full rounded-lg border px-3"/></label>)}</div>{manager ? <button className="mt-5 h-11 rounded-lg bg-[var(--clinic-primary)] px-5 text-sm font-black text-white">Salvar automações</button> : null}</form> : null}

    {active === "mensagens" ? <section className="premium-panel mt-6 rounded-lg p-5 sm:p-6"><h2 className="text-xl font-black">Mensagens</h2><p className="mt-1 text-sm text-neutral-500">Últimas 50 mensagens. Telefone não é exibido integralmente.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-[.1em] text-neutral-500"><th className="p-3">Data</th><th className="p-3">Cliente</th><th className="p-3">Gatilho</th><th className="p-3">Template</th><th className="p-3">Status</th><th className="p-3">Erro</th></tr></thead><tbody>{messages.map((item) => <tr key={item.id} className="border-b border-neutral-100"><td className="p-3">{date(item.created_at)}</td><td className="p-3 font-bold">{item.clientes?.nome || (item.direction === "inbound" ? "Contato recebido" : "-")}</td><td className="p-3">{PURPOSE_LABELS[item.trigger] || item.trigger || "Recebida"}</td><td className="p-3">{item.template_name || "-"}</td><td className="p-3 font-bold">{MESSAGE_LABELS[item.status] || item.status}</td><td className="max-w-xs p-3 text-red-700">{item.error_message || "-"}</td></tr>)}</tbody></table>{!messages.length ? <p className="py-10 text-center text-sm text-neutral-500">Nenhuma mensagem registrada.</p> : null}</div></section> : null}

    {active === "templates" ? <section className="premium-panel mt-6 rounded-lg p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">Templates Meta</h2><p className="mt-1 text-sm text-neutral-500">A sincronização exibe o estado retornado pela Meta. Pendente não é considerado pronto.</p></div>{manager && connection ? <div className="flex flex-wrap gap-2"><form action={submitWhatsAppTemplatesAction}><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-[var(--clinic-primary)] px-4 text-sm font-bold text-white">Enviar ausentes</button></form><form action={syncWhatsAppTemplatesAction}><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-neutral-950 px-4 text-sm font-bold text-white"><RefreshCw size={16}/> Sincronizar</button></form></div> : null}</div><div className="mt-5 grid gap-3 lg:grid-cols-2">{templates.map((item) => <article key={item.id} className="rounded-lg border border-neutral-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{PURPOSE_LABELS[item.purpose] || item.purpose}</p><p className="mt-1 text-xs text-neutral-500">{item.name} · {item.language} · {item.category}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${item.status === "APPROVED" ? "bg-emerald-50 text-emerald-700" : item.status === "REJECTED" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{STATUS_LABELS[item.status] || item.status}</span></div>{item.rejection_reason ? <p className="mt-3 text-sm text-red-700">{item.rejection_reason}</p> : null}<p className="mt-3 text-xs text-neutral-500">Última sincronização: {date(item.last_synced_at)}</p></article>)}</div>{!templates.length ? <p className="mt-6 rounded-lg border border-dashed p-8 text-center text-sm text-neutral-500">Conecte a WABA e envie os templates transacionais para análise da Meta.</p> : null}</section> : null}

    {active === "saude" ? <section className="mt-6 grid gap-4 lg:grid-cols-3"><div className="premium-panel rounded-lg p-5"><ShieldCheck className="text-emerald-600"/><h2 className="mt-3 font-black">Conexão</h2><div className="mt-4 space-y-3 text-sm"><p className="flex justify-between gap-3"><span>WABA conectada</span>{bool(Boolean(connection?.waba_id))}</p><p className="flex justify-between gap-3"><span>Número registrado</span>{bool(Boolean(connection?.phone_number_id))}</p><p className="flex justify-between gap-3"><span>Estado pronto</span>{bool(connection?.onboarding_status === "ready")}</p></div></div><div className="premium-panel rounded-lg p-5"><Webhook className="text-[var(--clinic-primary)]"/><h2 className="mt-3 font-black">Entrega</h2><div className="mt-4 space-y-3 text-sm"><p className="flex justify-between gap-3"><span>Templates aprovados</span><strong>{approved}/{templates.length}</strong></p><p className="flex justify-between gap-3"><span>Jobs pendentes</span><strong>{jobsResult.count || 0}</strong></p><p className="flex justify-between gap-3"><span>Falhas recentes</span><strong>{failedJobs}</strong></p></div></div><div className="premium-panel rounded-lg p-5"><Clock3 className="text-amber-600"/><h2 className="mt-3 font-black">Atividade</h2><div className="mt-4 space-y-3 text-sm"><p><span className="block text-neutral-500">Último webhook</span><strong>{date(webhookResult.data?.received_at || connection?.last_webhook_at)}</strong></p><p><span className="block text-neutral-500">Última mensagem</span><strong>{date(messages[0]?.created_at)}</strong></p><p><span className="block text-neutral-500">Número</span><strong>{maskPhone(connection?.display_phone_number)}</strong></p></div></div></section> : null}
  </section></main>;
}
