import { PageHeader, Field, SelectField, SubmitButton } from "@/components/app-shell/ui";
import { requireClinicSection } from "@/lib/auth/session";
import { getFinanceSettings, listFinanceRows, money, monthPeriod } from "@/lib/finance/service";
import { ExportCsvLink, FinancePage, FinanceTable, SchemaNotice, StatusPill } from "../shared";
import { createReceivableAction, settleReceivableAction } from "../actions";

export default async function ReceberPage({searchParams}) { const {activeClinic}=await requireClinicSection("financeiro"); const params=await searchParams; const period=monthPeriod(params?.month); const [result,settings]=await Promise.all([listFinanceRows("finance_recebiveis",activeClinic.id,{start:period.start,end:period.end,dateColumn:"vencimento",limit:250}),getFinanceSettings(activeClinic.id)]); return <FinancePage>
  <PageHeader eyebrow="Financeiro" title="Contas a receber" description="Obrigações geradas por atendimentos, pacotes, loja, gateways e lançamentos manuais." />
  <div className="mt-4"><ExportCsvLink report="receber" month={period.month} /></div>
  {!result.available ? <div className="mt-6"><SchemaNotice/></div> : <><div className="mt-6 grid gap-5 xl:grid-cols-[1fr_340px]"><FinanceTable rows={result.rows} columns={[
    {key:"descricao",label:"Descrição"},{key:"vencimento",label:"Vencimento"},{key:"valor_total",label:"Total",render:r=>money(r.valor_total)},{key:"aberto",label:"Em aberto",render:r=>money(Number(r.valor_total)-Number(r.valor_recebido))},{key:"status",label:"Status",render:r=><StatusPill status={r.status}/>}]} />
    <form action={createReceivableAction} className="premium-panel rounded-lg p-5"><h2 className="text-lg font-black">Novo recebível</h2><div className="mt-4 space-y-4"><Field label="Descrição" name="descricao" required/><Field label="Valor" name="valor" type="number" min="0.01" step="0.01" required/><Field label="Primeiro vencimento" name="vencimento" type="date" required/><Field label="Parcelas" name="parcelas" type="number" min="1" max="120" defaultValue="1"/><input type="hidden" name="categoria_codigo" value="REC_SERVICOS"/><SubmitButton>Adicionar</SubmitButton></div></form></div>
    <section className="premium-panel mt-6 rounded-lg p-5"><h2 className="text-lg font-black">Registrar recebimento</h2><form action={settleReceivableAction} className="mt-4 grid gap-4 md:grid-cols-5"><SelectField label="Recebível" name="recebivel_id" required><option value="">Selecione</option>{result.rows.filter(r=>["aberto","parcial"].includes(r.status)).map(r=><option key={r.id} value={r.id}>{r.descricao} · {money(Number(r.valor_total)-Number(r.valor_recebido))}</option>)}</SelectField><SelectField label="Conta" name="conta_id"><option value="">Conta padrão</option>{settings.accounts.map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</SelectField><Field label="Valor" name="valor" type="number" required/><Field label="Taxa" name="taxa" type="number" defaultValue="0"/><SelectField label="Forma" name="forma_pagamento"><option value="pix">Pix</option><option value="dinheiro">Dinheiro</option><option value="cartao">Cartão</option><option value="boleto">Boleto</option><option value="outro">Outro</option></SelectField><div className="md:col-span-5"><SubmitButton>Confirmar recebimento</SubmitButton></div></form></section></>}
</FinancePage>; }
