const field = (path, label, type, extra = {}) => Object.freeze({ path, label, type, ...extra });

export const EVENT_REGISTRY = Object.freeze({
  "crm.opportunity.created": {
    type: "crm.opportunity.created", label: "Oportunidade criada", module: "CRM", description: "Uma oportunidade foi criada no CRM.",
    entity: "crm_opportunity", schemaVersion: 1, capability: "crm",
    fields: [field("opportunity.id", "Oportunidade", "reference"), field("opportunity.stage_id", "Etapa", "reference"), field("opportunity.responsavel_id", "Responsável", "reference"), field("opportunity.valor_estimado", "Valor estimado", "money"), field("opportunity.temperatura", "Temperatura", "enum", { options: ["frio", "morno", "quente"] }), field("opportunity.score", "Score", "number"), field("opportunity.first_response_at", "Primeiro contato", "datetime")],
  },
  "crm.stage.changed": {
    type: "crm.stage.changed", label: "Etapa da oportunidade alterada", module: "CRM", description: "Uma oportunidade mudou de etapa.",
    entity: "crm_opportunity", schemaVersion: 1, capability: "crm",
    fields: [field("event.payload.from_stage_id", "Etapa anterior", "reference"), field("event.payload.to_stage_id", "Etapa atual", "reference"), field("opportunity.stage_id", "Etapa atual confirmada", "reference"), field("opportunity.responsavel_id", "Responsável", "reference"), field("opportunity.valor_estimado", "Valor estimado", "money"), field("opportunity.status", "Status", "enum")],
  },
  "crm.activity.created": { type: "crm.activity.created", label: "Atividade criada", module: "CRM", description: "Uma atividade foi criada.", entity: "crm_opportunity", schemaVersion: 1, capability: "crm", fields: [field("event.payload.activity_id", "Atividade", "reference"), field("event.payload.type", "Tipo", "enum"), field("opportunity.id", "Oportunidade", "reference")] },
  "crm.activity.completed": { type: "crm.activity.completed", label: "Atividade concluída", module: "CRM", description: "Uma atividade foi concluída.", entity: "crm_opportunity", schemaVersion: 1, capability: "crm", fields: [field("event.payload.activity_id", "Atividade", "reference"), field("opportunity.id", "Oportunidade", "reference")] },
  "crm.opportunity.won": { type: "crm.opportunity.won", label: "Oportunidade ganha", module: "CRM", description: "Uma oportunidade foi convertida.", entity: "crm_opportunity", schemaVersion: 1, capability: "crm", fields: [field("opportunity.valor_fechado", "Valor fechado", "money"), field("opportunity.responsavel_id", "Responsável", "reference")] },
  "crm.opportunity.lost": { type: "crm.opportunity.lost", label: "Oportunidade perdida", module: "CRM", description: "Uma oportunidade foi marcada como perdida.", entity: "crm_opportunity", schemaVersion: 1, capability: "crm", fields: [field("opportunity.lost_reason_id", "Motivo da perda", "reference"), field("opportunity.responsavel_id", "Responsável", "reference")] },
  "booking.created": { type: "booking.created", label: "Agendamento criado", module: "Agenda", description: "Um novo agendamento foi registrado.", entity: "booking", schemaVersion: 1, capability: "agenda", fields: [field("booking.status", "Status", "enum"), field("booking.inicio", "Início", "datetime"), field("booking.pagamento_status", "Pagamento", "enum"), field("booking.valor", "Valor", "money"), field("booking.profissional_id", "Profissional", "reference")] },
  "booking.rescheduled": { type: "booking.rescheduled", label: "Agendamento reagendado", module: "Agenda", description: "O horário de um agendamento foi alterado.", entity: "booking", schemaVersion: 1, capability: "agenda", fields: [field("booking.status", "Status", "enum"), field("booking.inicio", "Novo início", "datetime"), field("booking.profissional_id", "Profissional", "reference")] },
  "booking.cancelled": { type: "booking.cancelled", label: "Agendamento cancelado", module: "Agenda", description: "Um agendamento foi cancelado.", entity: "booking", schemaVersion: 1, capability: "agenda", fields: [field("booking.status", "Status", "enum"), field("booking.inicio", "Início", "datetime")] },
  "booking.completed": { type: "booking.completed", label: "Atendimento concluído", module: "Agenda", description: "Um atendimento foi concluído.", entity: "booking", schemaVersion: 1, capability: "agenda", fields: [field("booking.status", "Status", "enum"), field("booking.cliente_id", "Cliente", "reference"), field("booking.procedimento_id", "Procedimento", "reference"), field("booking.valor", "Valor", "money")] },
  "booking.no_show": { type: "booking.no_show", label: "Cliente faltou", module: "Agenda", description: "Um agendamento foi marcado como falta.", entity: "booking", schemaVersion: 1, capability: "agenda", fields: [field("booking.cliente_id", "Cliente", "reference"), field("booking.inicio", "Início", "datetime")] },
  "finance.receivable.created": { type: "finance.receivable.created", label: "Recebível criado", module: "Financeiro", description: "Uma nova obrigação a receber foi criada.", entity: "finance_receivable", schemaVersion: 1, capability: "financeiro", fields: [field("receivable.status", "Status", "enum"), field("receivable.vencimento", "Vencimento", "date"), field("receivable.valor_total", "Valor total", "money"), field("receivable.cliente_id", "Cliente", "reference")] },
  "finance.receivable.due_soon": { type: "finance.receivable.due_soon", label: "Recebível próximo do vencimento", module: "Financeiro", description: "Um recebível está próximo do vencimento.", entity: "finance_receivable", schemaVersion: 1, capability: "financeiro", fields: [field("receivable.status", "Status", "enum"), field("receivable.vencimento", "Vencimento", "date"), field("receivable.valor_total", "Valor total", "money")] },
  "finance.receivable.overdue": { type: "finance.receivable.overdue", label: "Recebível vencido", module: "Financeiro", description: "Um recebível segue pendente após o vencimento.", entity: "finance_receivable", schemaVersion: 1, capability: "financeiro", fields: [field("receivable.status", "Status", "enum"), field("receivable.vencimento", "Vencimento", "date"), field("receivable.valor_total", "Valor total", "money")] },
  "payment.received": { type: "payment.received", label: "Pagamento confirmado", module: "Financeiro", description: "Um pagamento foi confirmado pela fonte financeira.", entity: "finance_receivable", schemaVersion: 1, capability: "financeiro", fields: [field("receivable.status", "Status", "enum"), field("receivable.valor_recebido", "Valor recebido", "money"), field("receivable.agendamento_id", "Agendamento", "reference")] },
  "payment.partial": { type: "payment.partial", label: "Pagamento parcial", module: "Financeiro", description: "Um recebível recebeu pagamento parcial.", entity: "finance_receivable", schemaVersion: 1, capability: "financeiro", fields: [field("receivable.status", "Status", "enum"), field("receivable.valor_recebido", "Valor recebido", "money"), field("receivable.valor_total", "Valor total", "money")] },
});

export const EVENT_TYPES = Object.freeze(Object.keys(EVENT_REGISTRY));
export function getEventDefinition(type) { return EVENT_REGISTRY[type] || null; }
export function isRegisteredEvent(type) { return Boolean(getEventDefinition(type)); }
export function getEventField(type, path) { return getEventDefinition(type)?.fields.find((item) => item.path === path) || null; }
