-- E-commerce multi-tenant da clínica: catálogo, pedidos, cupons, estoque reservado e carrinhos recuperáveis.

create table if not exists public.produtos_clinica (
  id uuid primary key default gen_random_uuid(),
  clinica_id uuid not null references public.clinicas(id) on delete cascade,
  nome text not null,
  sku text,
  codigo_barras text,
  categoria text,
  descricao text,
  custo numeric(12,2) not null default 0 check (custo >= 0),
  preco numeric(12,2) not null default 0 check (preco >= 0),
  estoque_atual numeric(12,3) not null default 0 check (estoque_atual >= 0),
  estoque_reservado numeric(12,3) not null default 0 check (estoque_reservado >= 0),
  estoque_minimo numeric(12,3) not null default 0 check (estoque_minimo >= 0),
  unidade text not null default 'un',
  imagem_url text,
  publicado_site boolean not null default false,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clinica_id, id),
  unique (clinica_id, sku)
);

create index if not exists produtos_clinica_nome_idx on public.produtos_clinica (clinica_id, nome);
create index if not exists produtos_clinica_estoque_idx on public.produtos_clinica (clinica_id, ativo, estoque_atual);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'clientes_clinica_id_id_key') then
    alter table public.clientes add constraint clientes_clinica_id_id_key unique (clinica_id, id);
  end if;
end;
$$;

alter table public.produtos_clinica
  add column if not exists estoque_reservado numeric(12,3) not null default 0 check (estoque_reservado >= 0);

create table public.cupons_clinica (
  id uuid primary key default gen_random_uuid(),
  clinica_id uuid not null references public.clinicas(id) on delete cascade,
  codigo text not null,
  descricao text,
  tipo text not null check (tipo in ('percentual', 'fixo')),
  valor numeric(12,2) not null check (valor > 0),
  pedido_minimo numeric(12,2) not null default 0 check (pedido_minimo >= 0),
  desconto_maximo numeric(12,2) check (desconto_maximo is null or desconto_maximo > 0),
  limite_usos integer check (limite_usos is null or limite_usos > 0),
  usos integer not null default 0 check (usos >= 0),
  inicia_em timestamptz,
  termina_em timestamptz,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clinica_id, id)
);

create unique index cupons_clinica_codigo_idx
  on public.cupons_clinica (clinica_id, lower(codigo));
create index cupons_clinica_validade_idx
  on public.cupons_clinica (clinica_id, ativo, termina_em);

create table public.pedidos_clinica (
  id uuid primary key default gen_random_uuid(),
  clinica_id uuid not null references public.clinicas(id) on delete cascade,
  numero bigint generated by default as identity,
  token_publico uuid not null default gen_random_uuid() unique,
  cliente_id uuid,
  cupom_id uuid,
  status text not null default 'aguardando_pagamento' check (status in (
    'aguardando_pagamento', 'confirmado', 'em_separacao', 'pronto_retirada',
    'enviado', 'concluido', 'cancelado', 'estornado'
  )),
  pagamento_status text not null default 'pendente' check (pagamento_status in (
    'pendente', 'pago', 'falhou', 'cancelado', 'estornado', 'pagar_na_retirada'
  )),
  entrega_tipo text not null default 'retirada' check (entrega_tipo in ('retirada', 'entrega')),
  nome_cliente text not null,
  telefone_cliente text not null,
  email_cliente text,
  cpf_cliente text,
  cep text,
  endereco text,
  numero_endereco text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  referencia_entrega text,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  frete numeric(12,2) not null default 0 check (frete >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  cupom_codigo text,
  forma_pagamento text not null default 'UNDEFINED',
  asaas_payment_id text unique,
  invoice_url text,
  pago_em timestamptz,
  expiracao_reserva_em timestamptz,
  observacoes text,
  payload_pagamento jsonb not null default '{}'::jsonb,
  origem jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clinica_id, id),
  unique (clinica_id, numero),
  foreign key (clinica_id, cliente_id)
    references public.clientes(clinica_id, id) on delete restrict,
  foreign key (clinica_id, cupom_id)
    references public.cupons_clinica(clinica_id, id) on delete restrict
);

create index pedidos_clinica_status_idx
  on public.pedidos_clinica (clinica_id, status, created_at desc);
create index pedidos_clinica_pagamento_idx
  on public.pedidos_clinica (clinica_id, pagamento_status, created_at desc);
create index pedidos_clinica_cliente_idx
  on public.pedidos_clinica (clinica_id, cliente_id, created_at desc);
create index pedidos_clinica_reserva_idx
  on public.pedidos_clinica (status, expiracao_reserva_em)
  where status = 'aguardando_pagamento';

create table public.pedido_itens_clinica (
  id uuid primary key default gen_random_uuid(),
  clinica_id uuid not null references public.clinicas(id) on delete cascade,
  pedido_id uuid not null,
  produto_id uuid not null,
  nome_produto text not null,
  sku text,
  imagem_url text,
  quantidade numeric(12,3) not null check (quantidade > 0),
  valor_unitario numeric(12,2) not null check (valor_unitario >= 0),
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  total numeric(12,2) not null check (total >= 0),
  created_at timestamptz not null default now(),
  foreign key (clinica_id, pedido_id)
    references public.pedidos_clinica(clinica_id, id) on delete cascade,
  foreign key (clinica_id, produto_id)
    references public.produtos_clinica(clinica_id, id) on delete restrict
);

create index pedido_itens_clinica_pedido_idx
  on public.pedido_itens_clinica (clinica_id, pedido_id);
create index pedido_itens_clinica_produto_idx
  on public.pedido_itens_clinica (clinica_id, produto_id, created_at desc);

create table public.estoque_reservas_clinica (
  id uuid primary key default gen_random_uuid(),
  clinica_id uuid not null references public.clinicas(id) on delete cascade,
  pedido_id uuid not null,
  produto_id uuid not null,
  quantidade numeric(12,3) not null check (quantidade > 0),
  status text not null default 'ativa' check (status in ('ativa', 'convertida', 'liberada', 'expirada')),
  expira_em timestamptz not null,
  finalizada_em timestamptz,
  created_at timestamptz not null default now(),
  foreign key (clinica_id, pedido_id)
    references public.pedidos_clinica(clinica_id, id) on delete cascade,
  foreign key (clinica_id, produto_id)
    references public.produtos_clinica(clinica_id, id) on delete restrict,
  unique (pedido_id, produto_id)
);

create index estoque_reservas_clinica_ativas_idx
  on public.estoque_reservas_clinica (clinica_id, expira_em)
  where status = 'ativa';

create table public.estoque_movimentos_clinica (
  id uuid primary key default gen_random_uuid(),
  clinica_id uuid not null references public.clinicas(id) on delete cascade,
  produto_id uuid not null,
  pedido_id uuid,
  tipo text not null check (tipo in ('reserva', 'liberacao', 'venda', 'estorno', 'ajuste', 'entrada', 'saida')),
  quantidade numeric(12,3) not null,
  estoque_anterior numeric(12,3) not null,
  estoque_posterior numeric(12,3) not null,
  observacoes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  foreign key (clinica_id, produto_id)
    references public.produtos_clinica(clinica_id, id) on delete restrict,
  foreign key (clinica_id, pedido_id)
    references public.pedidos_clinica(clinica_id, id) on delete restrict
);

create index estoque_movimentos_clinica_produto_idx
  on public.estoque_movimentos_clinica (clinica_id, produto_id, created_at desc);

create table public.carrinhos_abandonados_clinica (
  id uuid primary key default gen_random_uuid(),
  clinica_id uuid not null references public.clinicas(id) on delete cascade,
  sessao_token uuid not null,
  token_recuperacao uuid not null default gen_random_uuid() unique,
  pedido_id uuid,
  status text not null default 'ativo' check (status in ('ativo', 'convertido', 'recuperado', 'expirado', 'descartado')),
  nome text,
  telefone text,
  email text,
  consentimento_recuperacao boolean not null default false,
  consentimento_em timestamptz,
  itens jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  cupom_codigo text,
  origem jsonb not null default '{}'::jsonb,
  ultima_interacao_em timestamptz not null default now(),
  lembrete_enviado_em timestamptz,
  quantidade_lembretes integer not null default 0 check (quantidade_lembretes >= 0),
  convertido_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clinica_id, id),
  unique (clinica_id, sessao_token),
  foreign key (clinica_id, pedido_id)
    references public.pedidos_clinica(clinica_id, id) on delete restrict
);

create index clinica_carrinhos_recuperacao_idx
  on public.carrinhos_abandonados_clinica (clinica_id, status, ultima_interacao_em desc);
create index clinica_carrinhos_lembrete_idx
  on public.carrinhos_abandonados_clinica (status, consentimento_recuperacao, ultima_interacao_em)
  where status = 'ativo' and consentimento_recuperacao = true;

create table if not exists public.pagamentos_loja_clinica (
  id uuid primary key default gen_random_uuid(),
  clinica_id uuid not null references public.clinicas(id) on delete cascade,
  cliente_id uuid,
  pedido_id uuid not null,
  valor numeric(12,2) not null default 0 check (valor >= 0),
  forma text not null default 'link' check (forma in ('pix', 'boleto', 'cartao_credito', 'dinheiro', 'link')),
  status text not null default 'pendente' check (status in ('pendente', 'pago', 'falhou', 'cancelado', 'estornado')),
  provedor text not null default 'asaas',
  provedor_pagamento_id text not null,
  link_pagamento text,
  pago_em timestamptz,
  vencimento_em timestamptz,
  payload jsonb not null default '{}'::jsonb,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clinica_id, provedor, provedor_pagamento_id),
  foreign key (clinica_id, cliente_id) references public.clientes(clinica_id, id) on delete restrict,
  foreign key (clinica_id, pedido_id) references public.pedidos_clinica(clinica_id, id) on delete restrict
);

create index if not exists pagamentos_loja_clinica_pedido_idx on public.pagamentos_loja_clinica (clinica_id, pedido_id);

create or replace function public.criar_pedido_loja(
  p_clinica_id uuid,
  p_cliente_id uuid,
  p_itens jsonb,
  p_nome text,
  p_telefone text,
  p_email text default null,
  p_cpf text default null,
  p_entrega_tipo text default 'retirada',
  p_frete numeric default 0,
  p_cep text default null,
  p_endereco text default null,
  p_numero_endereco text default null,
  p_complemento text default null,
  p_bairro text default null,
  p_cidade text default null,
  p_estado text default null,
  p_referencia_entrega text default null,
  p_cupom_codigo text default null,
  p_forma_pagamento text default 'UNDEFINED',
  p_reserva_minutos integer default 30,
  p_origem jsonb default '{}'::jsonb
)
returns table (pedido_id uuid, token_publico uuid, numero bigint, subtotal numeric, desconto numeric, frete numeric, total numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.pedidos_clinica%rowtype;
  v_produto public.produtos_clinica%rowtype;
  v_cupom public.cupons_clinica%rowtype;
  v_item record;
  v_subtotal numeric(12,2) := 0;
  v_desconto numeric(12,2) := 0;
  v_frete numeric(12,2) := greatest(coalesce(p_frete, 0), 0);
  v_total numeric(12,2) := 0;
  v_expira_em timestamptz := now() + make_interval(mins => greatest(10, least(coalesce(p_reserva_minutos, 30), 240)));
  v_item_count integer := 0;
begin
  if p_entrega_tipo not in ('retirada', 'entrega') then
    raise exception 'Forma de entrega invalida.';
  end if;

  if coalesce(trim(p_nome), '') = '' or coalesce(trim(p_telefone), '') = '' then
    raise exception 'Nome e telefone sao obrigatorios.';
  end if;

  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens) = 0 then
    raise exception 'O carrinho esta vazio.';
  end if;

  for v_item in
    select produto_id, sum(quantidade)::numeric(12,3) as quantidade
    from jsonb_to_recordset(p_itens) as item(produto_id uuid, quantidade numeric)
    group by produto_id
  loop
    v_item_count := v_item_count + 1;
    if v_item.quantidade <= 0 or v_item.quantidade <> trunc(v_item.quantidade) then
      raise exception 'Quantidade invalida no carrinho.';
    end if;

    select * into v_produto
    from public.produtos_clinica
    where id = v_item.produto_id
      and clinica_id = p_clinica_id
      and ativo = true
      and publicado_site = true
    for update;

    if not found then
      raise exception 'Produto indisponivel.';
    end if;

    if (v_produto.estoque_atual - v_produto.estoque_reservado) < v_item.quantidade then
      raise exception 'Estoque insuficiente para %.', v_produto.nome;
    end if;

    v_subtotal := v_subtotal + round(v_produto.preco * v_item.quantidade, 2);
  end loop;

  if v_item_count = 0 then
    raise exception 'O carrinho esta vazio.';
  end if;

  if coalesce(trim(p_cupom_codigo), '') <> '' then
    select * into v_cupom
    from public.cupons_clinica
    where clinica_id = p_clinica_id
      and lower(codigo) = lower(trim(p_cupom_codigo))
      and ativo = true
      and (inicia_em is null or inicia_em <= now())
      and (termina_em is null or termina_em >= now())
    for update;

    if not found then
      raise exception 'Cupom invalido ou expirado.';
    end if;
    if v_subtotal < v_cupom.pedido_minimo then
      raise exception 'Este cupom exige um pedido minimo de R$ %.', v_cupom.pedido_minimo;
    end if;
    if v_cupom.limite_usos is not null and v_cupom.usos >= v_cupom.limite_usos then
      raise exception 'O limite de uso deste cupom foi atingido.';
    end if;

    if v_cupom.tipo = 'percentual' then
      v_desconto := round(v_subtotal * (v_cupom.valor / 100), 2);
      if v_cupom.desconto_maximo is not null then
        v_desconto := least(v_desconto, v_cupom.desconto_maximo);
      end if;
    else
      v_desconto := least(v_cupom.valor, v_subtotal);
    end if;
  end if;

  v_total := greatest(round(v_subtotal - v_desconto + v_frete, 2), 0);

  insert into public.pedidos_clinica (
    clinica_id, cliente_id, cupom_id, nome_cliente, telefone_cliente, email_cliente, cpf_cliente,
    entrega_tipo, cep, endereco, numero_endereco, complemento, bairro, cidade, estado, referencia_entrega,
    subtotal, desconto, frete, total, cupom_codigo, forma_pagamento, expiracao_reserva_em, origem
  ) values (
    p_clinica_id, p_cliente_id, v_cupom.id, trim(p_nome), trim(p_telefone), nullif(trim(p_email), ''), nullif(trim(p_cpf), ''),
    p_entrega_tipo, nullif(trim(p_cep), ''), nullif(trim(p_endereco), ''), nullif(trim(p_numero_endereco), ''),
    nullif(trim(p_complemento), ''), nullif(trim(p_bairro), ''), nullif(trim(p_cidade), ''), nullif(trim(p_estado), ''),
    nullif(trim(p_referencia_entrega), ''), v_subtotal, v_desconto, v_frete, v_total, v_cupom.codigo,
    coalesce(nullif(trim(p_forma_pagamento), ''), 'UNDEFINED'), v_expira_em, coalesce(p_origem, '{}'::jsonb)
  ) returning * into v_pedido;

  for v_item in
    select produto_id, sum(quantidade)::numeric(12,3) as quantidade
    from jsonb_to_recordset(p_itens) as item(produto_id uuid, quantidade numeric)
    group by produto_id
  loop
    select * into v_produto
    from public.produtos_clinica
    where id = v_item.produto_id and clinica_id = p_clinica_id;

    update public.produtos_clinica
    set estoque_reservado = estoque_reservado + v_item.quantidade
    where id = v_produto.id and clinica_id = p_clinica_id;

    insert into public.pedido_itens_clinica (
      clinica_id, pedido_id, produto_id, nome_produto, sku, imagem_url,
      quantidade, valor_unitario, total
    ) values (
      p_clinica_id, v_pedido.id, v_produto.id, v_produto.nome, v_produto.sku, v_produto.imagem_url,
      v_item.quantidade, v_produto.preco, round(v_produto.preco * v_item.quantidade, 2)
    );

    insert into public.estoque_reservas_clinica (
      clinica_id, pedido_id, produto_id, quantidade, expira_em
    ) values (
      p_clinica_id, v_pedido.id, v_produto.id, v_item.quantidade, v_expira_em
    );

    insert into public.estoque_movimentos_clinica (
      clinica_id, produto_id, pedido_id, tipo, quantidade,
      estoque_anterior, estoque_posterior, observacoes
    ) values (
      p_clinica_id, v_produto.id, v_pedido.id, 'reserva', 0,
      v_produto.estoque_atual, v_produto.estoque_atual, 'Reserva temporaria do pedido online.'
    );
  end loop;

  if v_cupom.id is not null then
    update public.cupons_clinica set usos = usos + 1 where id = v_cupom.id;
  end if;

  return query select v_pedido.id, v_pedido.token_publico, v_pedido.numero,
    v_subtotal, v_desconto, v_frete, v_total;
end;
$$;

create or replace function public.cancelar_pedido_loja(p_pedido_id uuid, p_motivo text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.pedidos_clinica%rowtype;
  v_reserva public.estoque_reservas_clinica%rowtype;
  v_estoque numeric(12,3);
begin
  select * into v_pedido from public.pedidos_clinica where id = p_pedido_id for update;
  if not found then return false; end if;
  if v_pedido.status in ('cancelado', 'estornado') then return true; end if;
  if v_pedido.pagamento_status = 'pago' then
    raise exception 'Pedido pago deve ser estornado, nao cancelado.';
  end if;

  for v_reserva in
    select * from public.estoque_reservas_clinica
    where pedido_id = p_pedido_id and status = 'ativa'
    for update
  loop
    select estoque_atual into v_estoque
    from public.produtos_clinica
    where id = v_reserva.produto_id and clinica_id = v_reserva.clinica_id
    for update;

    update public.produtos_clinica
    set estoque_reservado = greatest(estoque_reservado - v_reserva.quantidade, 0)
    where id = v_reserva.produto_id and clinica_id = v_reserva.clinica_id;

    update public.estoque_reservas_clinica
    set status = case when expira_em <= now() then 'expirada' else 'liberada' end,
        finalizada_em = now()
    where id = v_reserva.id;

    insert into public.estoque_movimentos_clinica (
      clinica_id, produto_id, pedido_id, tipo, quantidade,
      estoque_anterior, estoque_posterior, observacoes
    ) values (
      v_reserva.clinica_id, v_reserva.produto_id, p_pedido_id, 'liberacao', 0,
      v_estoque, v_estoque, coalesce(p_motivo, 'Reserva liberada.')
    );
  end loop;

  if v_pedido.cupom_id is not null then
    update public.cupons_clinica set usos = greatest(usos - 1, 0) where id = v_pedido.cupom_id;
  end if;

  update public.pedidos_clinica
  set status = 'cancelado', pagamento_status = 'cancelado',
      observacoes = concat_ws(E'\n', observacoes, p_motivo)
  where id = p_pedido_id;
  return true;
end;
$$;

create or replace function public.confirmar_pagamento_pedido_loja(
  p_pedido_id uuid,
  p_asaas_payment_id text default null,
  p_payload jsonb default '{}'::jsonb,
  p_pago_em timestamptz default now()
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.pedidos_clinica%rowtype;
  v_reserva public.estoque_reservas_clinica%rowtype;
  v_produto public.produtos_clinica%rowtype;
begin
  select * into v_pedido from public.pedidos_clinica where id = p_pedido_id for update;
  if not found then return false; end if;
  if v_pedido.pagamento_status = 'pago' then return true; end if;
  if v_pedido.status in ('cancelado', 'estornado') then
    raise exception 'Pedido cancelado nao pode ser confirmado.';
  end if;

  for v_reserva in
    select * from public.estoque_reservas_clinica
    where pedido_id = p_pedido_id and status = 'ativa'
    for update
  loop
    select * into v_produto
    from public.produtos_clinica
    where id = v_reserva.produto_id and clinica_id = v_reserva.clinica_id
    for update;

    if v_produto.estoque_atual < v_reserva.quantidade then
      raise exception 'Estoque inconsistente para confirmar o pedido.';
    end if;

    update public.produtos_clinica
    set estoque_atual = estoque_atual - v_reserva.quantidade,
        estoque_reservado = greatest(estoque_reservado - v_reserva.quantidade, 0)
    where id = v_produto.id and clinica_id = v_produto.clinica_id;

    update public.estoque_reservas_clinica
    set status = 'convertida', finalizada_em = now()
    where id = v_reserva.id;

    insert into public.estoque_movimentos_clinica (
      clinica_id, produto_id, pedido_id, tipo, quantidade,
      estoque_anterior, estoque_posterior, observacoes
    ) values (
      v_produto.clinica_id, v_produto.id, p_pedido_id, 'venda', -v_reserva.quantidade,
      v_produto.estoque_atual, v_produto.estoque_atual - v_reserva.quantidade,
      'Venda confirmada pelo pagamento do pedido online.'
    );
  end loop;

  update public.pedidos_clinica
  set status = 'em_separacao', pagamento_status = 'pago', pago_em = coalesce(p_pago_em, now()),
      asaas_payment_id = coalesce(p_asaas_payment_id, asaas_payment_id),
      payload_pagamento = coalesce(p_payload, '{}'::jsonb)
  where id = p_pedido_id;
  return true;
end;
$$;

create or replace function public.estornar_pedido_loja(p_pedido_id uuid, p_motivo text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.pedidos_clinica%rowtype;
  v_item public.pedido_itens_clinica%rowtype;
  v_estoque numeric(12,3);
begin
  select * into v_pedido from public.pedidos_clinica where id = p_pedido_id for update;
  if not found then return false; end if;
  if v_pedido.status = 'estornado' then return true; end if;
  if v_pedido.pagamento_status <> 'pago' then
    raise exception 'Somente pedidos pagos podem ser estornados.';
  end if;

  for v_item in select * from public.pedido_itens_clinica where pedido_id = p_pedido_id
  loop
    select estoque_atual into v_estoque
    from public.produtos_clinica
    where id = v_item.produto_id and clinica_id = v_item.clinica_id
    for update;

    update public.produtos_clinica
    set estoque_atual = estoque_atual + v_item.quantidade
    where id = v_item.produto_id and clinica_id = v_item.clinica_id;

    insert into public.estoque_movimentos_clinica (
      clinica_id, produto_id, pedido_id, tipo, quantidade,
      estoque_anterior, estoque_posterior, observacoes
    ) values (
      v_item.clinica_id, v_item.produto_id, p_pedido_id, 'estorno', v_item.quantidade,
      v_estoque, v_estoque + v_item.quantidade, coalesce(p_motivo, 'Estorno do pedido online.')
    );
  end loop;

  if v_pedido.cupom_id is not null then
    update public.cupons_clinica set usos = greatest(usos - 1, 0) where id = v_pedido.cupom_id;
  end if;

  update public.pedidos_clinica
  set status = 'estornado', pagamento_status = 'estornado',
      observacoes = concat_ws(E'\n', observacoes, p_motivo)
  where id = p_pedido_id;
  return true;
end;
$$;

create or replace function public.expirar_pedidos_loja()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido record;
  v_total integer := 0;
begin
  for v_pedido in
    select id from public.pedidos_clinica
    where status = 'aguardando_pagamento'
      and pagamento_status = 'pendente'
      and expiracao_reserva_em < now()
    for update skip locked
  loop
    perform public.cancelar_pedido_loja(v_pedido.id, 'Reserva expirada automaticamente.');
    v_total := v_total + 1;
  end loop;
  return v_total;
end;
$$;

revoke all on function public.criar_pedido_loja(uuid, uuid, jsonb, text, text, text, text, text, numeric, text, text, text, text, text, text, text, text, text, text, integer, jsonb) from public, anon, authenticated;
revoke all on function public.cancelar_pedido_loja(uuid, text) from public, anon, authenticated;
revoke all on function public.confirmar_pagamento_pedido_loja(uuid, text, jsonb, timestamptz) from public, anon, authenticated;
revoke all on function public.estornar_pedido_loja(uuid, text) from public, anon, authenticated;
revoke all on function public.expirar_pedidos_loja() from public, anon, authenticated;

grant execute on function public.criar_pedido_loja(uuid, uuid, jsonb, text, text, text, text, text, numeric, text, text, text, text, text, text, text, text, text, text, integer, jsonb) to service_role;
grant execute on function public.cancelar_pedido_loja(uuid, text) to service_role;
grant execute on function public.confirmar_pagamento_pedido_loja(uuid, text, jsonb, timestamptz) to service_role;
grant execute on function public.estornar_pedido_loja(uuid, text) to service_role;
grant execute on function public.expirar_pedidos_loja() to service_role;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'cupons_clinica', 'pedidos_clinica', 'pedido_itens_clinica',
    'estoque_reservas_clinica', 'estoque_movimentos_clinica', 'carrinhos_abandonados_clinica'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;

  foreach table_name in array array['cupons_clinica', 'pedidos_clinica', 'carrinhos_abandonados_clinica']
  loop
    execute format(
      'create trigger %I before update on public.%I for each row execute function app_private.set_updated_at()',
      'set_updated_at_' || table_name, table_name
    );
  end loop;
end;
$$;

create policy cupons_clinica_crud_membros on public.cupons_clinica
  for all to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id))
  with check (app_private.usuario_tem_acesso_clinica(clinica_id));
create policy pedidos_clinica_crud_membros on public.pedidos_clinica
  for all to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id))
  with check (app_private.usuario_tem_acesso_clinica(clinica_id));
create policy pedido_itens_clinica_crud_membros on public.pedido_itens_clinica
  for all to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id))
  with check (app_private.usuario_tem_acesso_clinica(clinica_id));
create policy estoque_reservas_clinica_crud_membros on public.estoque_reservas_clinica
  for all to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id))
  with check (app_private.usuario_tem_acesso_clinica(clinica_id));
create policy estoque_movimentos_clinica_crud_membros on public.estoque_movimentos_clinica
  for all to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id))
  with check (app_private.usuario_tem_acesso_clinica(clinica_id));
create policy clinica_carrinhos_select_membros on public.carrinhos_abandonados_clinica
  for select to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id));
create policy clinica_carrinhos_update_membros on public.carrinhos_abandonados_clinica
  for update to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id))
  with check (app_private.usuario_tem_acesso_clinica(clinica_id));

grant select, insert, update, delete on public.cupons_clinica, public.pedidos_clinica,
  public.pedido_itens_clinica, public.estoque_reservas_clinica, public.estoque_movimentos_clinica
  to authenticated;
grant select, update on public.carrinhos_abandonados_clinica to authenticated;
grant all privileges on public.cupons_clinica, public.pedidos_clinica, public.pedido_itens_clinica,
  public.estoque_reservas_clinica, public.estoque_movimentos_clinica, public.carrinhos_abandonados_clinica
  to service_role;
grant usage, select on sequence public.pedidos_clinica_numero_seq to authenticated, service_role;

comment on table public.pedidos_clinica is 'Pedidos de produtos originados na lojinha publica da clínica.';
comment on table public.carrinhos_abandonados_clinica is 'Carrinhos persistidos para metricas e recuperacao com consentimento.';
comment on column public.produtos_clinica.estoque_reservado is 'Quantidade temporariamente reservada por pedidos ainda nao pagos.';


drop trigger if exists set_updated_at_produtos_clinica on public.produtos_clinica;
create trigger set_updated_at_produtos_clinica before update on public.produtos_clinica
for each row execute function app_private.set_updated_at();
drop trigger if exists set_updated_at_pagamentos_loja_clinica on public.pagamentos_loja_clinica;
create trigger set_updated_at_pagamentos_loja_clinica before update on public.pagamentos_loja_clinica
for each row execute function app_private.set_updated_at();

alter table public.produtos_clinica enable row level security;
alter table public.pagamentos_loja_clinica enable row level security;

create policy produtos_clinica_crud_membros on public.produtos_clinica
  for all to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id))
  with check (app_private.usuario_tem_acesso_clinica(clinica_id));
create policy pagamentos_loja_clinica_crud_membros on public.pagamentos_loja_clinica
  for all to authenticated
  using (app_private.usuario_tem_acesso_clinica(clinica_id))
  with check (app_private.usuario_tem_acesso_clinica(clinica_id));

grant select, insert, update, delete on public.produtos_clinica, public.pagamentos_loja_clinica to authenticated;
grant all privileges on public.produtos_clinica, public.pagamentos_loja_clinica to service_role;
